services:
  dagster:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home  # Mount your dagster_home directory
